[workspace]
members = ["backend", "frontend", "shared", "database", "database/migration", "database/entity"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

